' ******************************************************************************
' swxJRNL.swj - journal recorded on 04/09/24 by Darren Au
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "main_frame", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Part.SetPickMode

' Open
Set Part = swApp.OpenDoc6("C:\Users\darren\Documents\Solidworks\RC_Car\full_Car.SLDASM", 2, 0, "", longstatus, longwarnings)
Dim swAssembly As Object
Set swAssembly = Part
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 44
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "full_Car", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.6307987354444783978, 0.1607756240366544909

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03472286617125568825, -0.02217594814298682812
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01157428872375189551, -0.01108797407149341406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.008680716542813922063, -0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01446786090468986895, -0.01108797407149341406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01157428872375189551, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01446786090468986895, -0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.008680716542813922063, -0.01108797407149341406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01157428872375189551, -0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01446786090468986895, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.008680716542813922063, -0.01108797407149341406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01157428872375189551, -0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.008680716542813922063, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.008680716542813922063, -0.01108797407149341406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01446786090468986895, -0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0289357218093797379, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02604214962844176792, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02314857744750379101, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02025500526656581757, -0.01108797407149341406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02314857744750379101, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0289357218093797379, -0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02314857744750379101, -0.01108797407149341406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02025500526656581757, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02314857744750379101, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02604214962844176792, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0289357218093797379, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03472286617125568825, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02314857744750379101, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03472286617125568825, 0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02025500526656581757, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01446786090468986895, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01157428872375189551, 0.01108797407149341406
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01446786090468986895, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.008680716542813922063, 0.01663196110724012022
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02025500526656581757, 0.00554398703574670703
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01446786090468986895, 0.01663196110724012022
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0.01663196110724012022
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02025500526656581757, 0.01663196110724012022
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02314857744750379101, 0.01663196110724012022
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02025500526656581757, 0.02771993517873353255
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02314857744750379101, 0.01663196110724012022
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02025500526656581757, 0.02217594814298682812
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02604214962844176792, 0.02771993517873353255
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01736143308562784413, 0.01663196110724012022

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Pan
Set swModelView = Part.ActiveView
swModelView.TranslateBy 0.007438571428571428071, 0.03791857142857142648

' Named View
Part.ShowNamedView2 "*Right", 4
Part.ViewZoomtofit2
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.01663196110724012022, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01663196110724012022, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0.01108797407149341406, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00554398703574670703, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.01108797407149341406, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00554398703574670703, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0.01108797407149341406, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.00554398703574670703, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.01663196110724012022, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.01663196110724012022, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01108797407149341406, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.01108797407149341406, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0.00554398703574670703, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01108797407149341406, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.0444499999999834472, 0.004365119404151370994, -0.2003911370890318067

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.01381358439221003209, 0.02563204797058915574, -0.1877453446390120462, -0.9845009004932087082, -0.07207348955999694218, -0.1598855497870473319, 0.0002227155682017148029, 2, True, 0, 0)

' Pan
Set swModelView = Part.ActiveView
swModelView.TranslateBy 0.1079500000000000043, -0.04045857142857142708
boolstatus = Part.Extension.SelectByRay(0.02605702711122148685, 0.03992997858026114955, -0.1250486515293260936, -0.9845009004932087082, -0.07207348955999694218, -0.1598855497870473319, 0.0001056970692741437143, 2, True, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02217594814298682812, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01663196110724012022, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00554398703574670703, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01108797407149341406, 0.01269999999988158379, 0.02259085924929848943, -0.1622007592089858008

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Pan
Set swModelView = Part.ActiveView
swModelView.TranslateBy -0.04481285714285714733, 0.02485571428571428654
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03182929399031771828, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02314857744750379101, 0.01663196110724012022, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02604214962844176792, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02025500526656581757, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02314857744750379101, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.00554398703574670703, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, -0.01108797407149341406, 0.01269999999982474037, 0.0262130541394505201, -0.1702579652636853069

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Part.SetPickMode
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.00554398703574670703, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.01108797407149341406, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.00554398703574670703, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02025500526656581757, 0.01108797407149341406, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.00554398703574670703, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0.01108797407149341406, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.00554398703574670703, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.01108797407149341406, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.00554398703574670703, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.01108797407149341406, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01108797407149341406, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0.00554398703574670703, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01108797407149341406, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.0444499999999834472, 0.01495983643049214606, -0.1860321305980079387

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02604214962844176792, 0.02771993517873353255, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02314857744750379101, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02025500526656581757, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02025500526656581757, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02025500526656581757, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02025500526656581757, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.01663196110724012022, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01736143308562784413, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01157428872375189551, 0, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01446786090468986895, 0.01108797407149341406, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008680716542813922063, 0.00554398703574670703, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.005787144361875947753, 0, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.002893572180937973876, 0, 0.04444999999981291694, 0.01713017043800846295, -0.1864973473622484335

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByRay(0.01304407835789334058, 0.0217405229506653086, -0.1796530560940254873, -0.4572192085011429485, -0.7701597142388155737, -0.4447523017828848291, 0.0001233273956797012504, 2, True, 0, 0)

' Pan
Set swModelView = Part.ActiveView
swModelView.TranslateBy 0.0433614285714285716, -0.01995714285714286426
boolstatus = Part.Extension.SelectByRay(0.01368878052772970477, 0.05054766713089975383, -0.1225974693995226517, -0.4572192085011429485, -0.7701597142388155737, -0.4447523017828848291, 0.0001462240545043008949, 1, True, 0, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02025500526656581757, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02604214962844176792, -0.02217594814298682812, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02314857744750379101, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.02771993517873353255, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, -0.01663196110724012022, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01157428872375189551, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, -0.00554398703574670703, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, -0.01108797407149341406, -0.0007881424904780942597, 0.0217436799850929674, -0.1601966993292762709

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0.01108797407149341406, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0.00554398703574670703, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01736143308562784413, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02025500526656581757, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01446786090468986895, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008680716542813922063, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.002893572180937973876, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.005787144361875947753, 0, 0.007842747527433857613, 0.03183605130135447325, -0.1672797177836047311

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Named View
Part.ShowNamedView2 "*Right", 4
Part.ViewZoomtofit2
' MSGBOX
' Save changes to full_Car?


' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Part.ClearSelection2 True
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "main_frame", False, longstatus
Set Part = swApp.ActiveDoc
swApp.ExitApp
End Sub
